CREATE TABLE TASK_GROUPS (
                      ID INT PRIMARY KEY AUTO_INCREMENT,
                      DESCRIPTION VARCHAR(100) NOT NULL,
                      DONE BIT
);
ALTER TABLE TASKS ADD COLUMN TASK_GROUP_ID INT NULL;
ALTER TABLE TASKS
    ADD FOREIGN KEY (TASK_GROUP_ID) REFERENCES TASK_GROUPS (ID);